///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CategoryDataImageImage {
/*
{
  "url": "https://res.cloudinary.com/delta-santhai/image/upload/v1638527320/Media-Upload/oe4aglqvkrauavng45zx.png",
  "filename": "Media-Upload/oe4aglqvkrauavng45zx"
} 
*/

  String? url;
  String? filename;
  Map<String, dynamic> __origJson = {};

  CategoryDataImageImage({
    this.url,
    this.filename,
  });
  CategoryDataImageImage.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    url = json['url']?.toString();
    filename = json['filename']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['url'] = url;
    data['filename'] = filename;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CategoryDataImage {
/*
{
  "image": {
    "url": "https://res.cloudinary.com/delta-santhai/image/upload/v1638527320/Media-Upload/oe4aglqvkrauavng45zx.png",
    "filename": "Media-Upload/oe4aglqvkrauavng45zx"
  },
  "_id": "61a9f15804f543a37e427a43",
  "createdBy": "61a70208d225eadb3cc1fe29",
  "createdAt": "2021-12-03T09:08:47.716Z",
  "__v": 0
} 
*/

  CategoryDataImageImage? image;
  String? Id;
  String? createdBy;
  String? createdAt;
  //int? _V;
  Map<String, dynamic> __origJson = {};

  CategoryDataImage({
    this.image,
    this.Id,
    this.createdBy,
    this.createdAt,
    //this._V,
  });
  CategoryDataImage.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    image = (json['image'] != null && (json['image'] is Map))
        ? CategoryDataImageImage.fromJson(json['image'])
        : null;
    Id = json['_id']?.toString();
    createdBy = json['createdBy']?.toString();
    createdAt = json['createdAt']?.toString();
    // _V = int.tryParse(json['__v']?.toString() ?? '');
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (image != null) {
      data['image'] = image!.toJson();
    }
    data['_id'] = Id;
    data['createdBy'] = createdBy;
    data['createdAt'] = createdAt;
    //data['__v'] = _V;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CategoryData {
/*
{
  "createdAt": "2021-12-18T15:32:49.914Z",
  "lastUpdatedAt": "2021-12-18T15:32:49.914Z",
  "_id": "Intel",
  "name": "Intel",
  "image": {
    "image": {
      "url": "https://res.cloudinary.com/delta-santhai/image/upload/v1638527320/Media-Upload/oe4aglqvkrauavng45zx.png",
      "filename": "Media-Upload/oe4aglqvkrauavng45zx"
    },
    "_id": "61a9f15804f543a37e427a43",
    "createdBy": "61a70208d225eadb3cc1fe29",
    "createdAt": "2021-12-03T09:08:47.716Z",
    "__v": 0
  },
  "__v": 0,
  "isActive": true,
  "isPopular": true,
  "priority": 1,
  "description": "",
  "website": "",
  "createdBy": "617a364be4e8f01513c409b1",
  "lastUpdatedBy": "617a364be4e8f01513c409b1"
} 
*/

  String? createdAt;
  String? lastUpdatedAt;
  String? Id;
  String? name;
  CategoryDataImage? image;
  //int? _V;
  bool? isActive;
  bool? isPopular;
  int? priority;
  String? description;
  String? website;
  String? createdBy;
  String? lastUpdatedBy;
  Map<String, dynamic> __origJson = {};

  CategoryData({
    this.createdAt,
    this.lastUpdatedAt,
    this.Id,
    this.name,
    this.image,
    //this._V,
    this.isActive,
    this.isPopular,
    this.priority,
    this.description,
    this.website,
    this.createdBy,
    this.lastUpdatedBy,
  });
  CategoryData.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    createdAt = json['createdAt']?.toString();
    lastUpdatedAt = json['lastUpdatedAt']?.toString();
    Id = json['_id']?.toString();
    name = json['name']?.toString();
    image = (json['image'] != null && (json['image'] is Map))
        ? CategoryDataImage.fromJson(json['image'])
        : null;
    //_V = int.tryParse(json['__v']?.toString() ?? '');
    isActive = json['isActive'];
    isPopular = json['isPopular'];
    priority = int.tryParse(json['priority']?.toString() ?? '');
    description = json['description']?.toString();
    website = json['website']?.toString();
    createdBy = json['createdBy']?.toString();
    lastUpdatedBy = json['lastUpdatedBy']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['createdAt'] = createdAt;
    data['lastUpdatedAt'] = lastUpdatedAt;
    data['_id'] = Id;
    data['name'] = name;
    if (image != null) {
      data['image'] = image!.toJson();
    }
    //data['__v'] = _V;
    data['isActive'] = isActive;
    data['isPopular'] = isPopular;
    data['priority'] = priority;
    data['description'] = description;
    data['website'] = website;
    data['createdBy'] = createdBy;
    data['lastUpdatedBy'] = lastUpdatedBy;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class Category {
/*
{
  "message": "Brands retrived",
  "status": "success",
  "data": [
    {
      "createdAt": "2021-12-18T15:32:49.914Z",
      "lastUpdatedAt": "2021-12-18T15:32:49.914Z",
      "_id": "Intel",
      "name": "Intel",
      "image": {
        "image": {
          "url": "https://res.cloudinary.com/delta-santhai/image/upload/v1638527320/Media-Upload/oe4aglqvkrauavng45zx.png",
          "filename": "Media-Upload/oe4aglqvkrauavng45zx"
        },
        "_id": "61a9f15804f543a37e427a43",
        "createdBy": "61a70208d225eadb3cc1fe29",
        "createdAt": "2021-12-03T09:08:47.716Z",
        "__v": 0
      },
      "__v": 0,
      "isActive": true,
      "isPopular": true,
      "priority": 1,
      "description": "",
      "website": "",
      "createdBy": "617a364be4e8f01513c409b1",
      "lastUpdatedBy": "617a364be4e8f01513c409b1"
    }
  ]
} 
*/

  String? message;
  String? status;
  List<CategoryData?>? data;
  Map<String, dynamic> __origJson = {};

  Category({
    this.message,
    this.status,
    this.data,
  });
  Category.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    message = json['message']?.toString();
    status = json['status']?.toString();
    if (json['data'] != null && (json['data'] is List)) {
      final v = json['data'];
      final arr0 = <CategoryData>[];
      v.forEach((v) {
        arr0.add(CategoryData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['message'] = message;
    data['status'] = status;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}
