///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class servicesDataServiceCentersServiceLocation {
/*
{
  "addressLine1": "78, ABC",
  "addressLine2": "Main Street",
  "city": "Chennai",
  "state": "Tamil Nadu",
  "pincode": 600001
} 
*/

  String? addressLine1;
  String? addressLine2;
  String? city;
  String? state;
  int? pincode;

  servicesDataServiceCentersServiceLocation({
    this.addressLine1,
    this.addressLine2,
    this.city,
    this.state,
    this.pincode,
  });
  servicesDataServiceCentersServiceLocation.fromJson(
      Map<String, dynamic> json) {
    addressLine1 = json['addressLine1']?.toString();
    addressLine2 = json['addressLine2']?.toString();
    city = json['city']?.toString();
    state = json['state']?.toString();
    pincode = json['pincode']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['addressLine1'] = addressLine1;
    data['addressLine2'] = addressLine2;
    data['city'] = city;
    data['state'] = state;
    data['pincode'] = pincode;
    return data;
  }
}

class servicesDataServiceCenters {
/*
{
  "serviceLocation": {
    "addressLine1": "78, ABC",
    "addressLine2": "Main Street",
    "city": "Chennai",
    "state": "Tamil Nadu",
    "pincode": 600001
  },
  "_id": "61e2684564a0d37e486cdf62",
  "name": "center name",
  "brands": [
    "Intel"
  ],
  "phone": 9875965656,
  "description": "Test description",
  "website": "www.centerName.comm",
  "createdBy": "61a70208d225eadb3cc1fe29",
  "createdAt": "2022-01-15T06:26:27.000Z",
  "__v": 0
} 
*/

  servicesDataServiceCentersServiceLocation? serviceLocation;
  String? Id;
  String? name;
  List<String?>? brands;
  int? phone;
  String? description;
  String? website;
  String? createdBy;
  String? createdAt;
  int? V;
  String? map;
  String? landline;

  servicesDataServiceCenters(
      {this.serviceLocation,
      this.Id,
      this.name,
      this.brands,
      this.phone,
      this.description,
      this.website,
      this.createdBy,
      this.createdAt,
      this.V,
      this.map,
      this.landline});
  servicesDataServiceCenters.fromJson(Map<String, dynamic> json) {
    serviceLocation = (json['serviceLocation'] != null)
        ? servicesDataServiceCentersServiceLocation
            .fromJson(json['serviceLocation'])
        : null;
    Id = json['_id']?.toString();
    name = json['name']?.toString();
    if (json['brands'] != null) {
      final v = json['brands'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      brands = arr0;
    }
    phone = json['phone']?.toInt();
    description = json['description']?.toString();
    website = json['website']?.toString();
    createdBy = json['createdBy']?.toString();
    createdAt = json['createdAt']?.toString();
    V = json['__v']?.toInt();
    map = json['map']?.toString();
    landline = json['landline']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (serviceLocation != null) {
      data['serviceLocation'] = serviceLocation!.toJson();
    }
    data['_id'] = Id;
    data['name'] = name;
    if (brands != null) {
      final v = brands;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['brands'] = arr0;
    }
    data['phone'] = phone;
    data['description'] = description;
    data['website'] = website;
    data['createdBy'] = createdBy;
    data['createdAt'] = createdAt;
    data['__v'] = V;
    data['map'] = map;
    data['landline'] = landline;
    return data;
  }
}

class servicesData {
/*
{
  "serviceCenters": [
    {
      "serviceLocation": {
        "addressLine1": "78, ABC",
        "addressLine2": "Main Street",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "pincode": 600001
      },
      "_id": "61e2684564a0d37e486cdf62",
      "name": "center name",
      "brands": [
        "Intel"
      ],
      "phone": 9875965656,
      "description": "Test description",
      "website": "www.centerName.comm",
      "createdBy": "61a70208d225eadb3cc1fe29",
      "createdAt": "2022-01-15T06:26:27.000Z",
      "__v": 0
    }
  ]
} 
*/

  List<servicesDataServiceCenters?>? serviceCenters;

  servicesData({
    this.serviceCenters,
  });
  servicesData.fromJson(Map<String, dynamic> json) {
    if (json['serviceCenters'] != null) {
      final v = json['serviceCenters'];
      final arr0 = <servicesDataServiceCenters>[];
      v.forEach((v) {
        arr0.add(servicesDataServiceCenters.fromJson(v));
      });
      serviceCenters = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (serviceCenters != null) {
      final v = serviceCenters;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['serviceCenters'] = arr0;
    }
    return data;
  }
}

class services {
/*
{
  "message": "All Service centers are retrieved",
  "status": "success",
  "data": {
    "serviceCenters": [
      {
        "serviceLocation": {
          "addressLine1": "78, ABC",
          "addressLine2": "Main Street",
          "city": "Chennai",
          "state": "Tamil Nadu",
          "pincode": 600001
        },
        "_id": "61e2684564a0d37e486cdf62",
        "name": "center name",
        "brands": [
          "Intel"
        ],
        "phone": 9875965656,
        "description": "Test description",
        "website": "www.centerName.comm",
        "createdBy": "61a70208d225eadb3cc1fe29",
        "createdAt": "2022-01-15T06:26:27.000Z",
        "__v": 0
      }
    ]
  }
} 
*/

  String? message;
  String? status;
  servicesData? data;

  services({
    this.message,
    this.status,
    this.data,
  });
  services.fromJson(Map<String, dynamic> json) {
    message = json['message']?.toString();
    status = json['status']?.toString();
    data = (json['data'] != null) ? servicesData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['message'] = message;
    data['status'] = status;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
